package io.skis.testmodel.pet;

import io.skis.annotations.Column;
import io.skis.annotations.Id;
import io.skis.annotations.SkisEntity;
import io.skis.annotations.Table;
import io.skis.annotations.Transient;
import io.skis.annotations.Version;
import java.math.BigDecimal;

/** Entity used to inspect and smoke-test the sources generated by the SKIS processor. */
@SkisEntity
@Table(schema = "shelter", name = "pet")
public record Pet(
    @Id long id,
    @Column(name = "pet_name", nullable = false, length = 200) String name,
    @Column(nullable = false, precision = 6, scale = 2) BigDecimal weight,
    @Column(nullable = false) boolean adopted,
    @Version long version,
    @Transient String displayLabel) {}
