<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.xhufang</groupId>
    <artifactId>skis-parent</artifactId>
    <version>0.2.1-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>skis-integration-tests</artifactId>
  <name>skis-integration-tests</name>
  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>
  <description>Dialect and transaction integration-test module</description>
  <dependencies>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-runtime</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-mutation</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-mapping</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-dialect-postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-dialect-h2</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-test-model</artifactId>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
