package io.skis.testmodel.book;

import io.skis.annotations.Column;
import io.skis.annotations.Id;
import io.skis.annotations.SkisEntity;
import io.skis.annotations.Table;
import io.skis.annotations.Transient;
import io.skis.annotations.Version;
import java.math.BigDecimal;

/** Entity used to inspect and smoke-test the sources generated by the SKIS processor. */
@SkisEntity
@Table(catalog = "library", schema = "inventory", name = "book")
public record Book(
    @Id long id,
    @Column(name = "book_name", nullable = false, length = 200) String name,
    @Column(nullable = false, precision = 12, scale = 2) BigDecimal price,
    @Column(nullable = false) boolean published,
    @Version long version,
    @Transient String displayLabel) {}
