<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.skis</groupId>
    <artifactId>skis-parent</artifactId>
    <version>0.0.2-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>skis-dialect-db2</artifactId>
  <name>SKIS DB2 Dialect</name>
  <description>IBM Db2 SQL dialect</description>
  <dependencies>
    <dependency>
      <groupId>io.skis</groupId>
      <artifactId>skis-dialect-api</artifactId>
    </dependency>
  </dependencies>
</project>
