package io.skis.processor;

import java.util.Locale;

final class SourceText {

  static final int GENERATED_ABI = 1;
  static final String GENERATED_COMMENT = "// Generated by SKIS. Do not edit.\n";
  static final String GENERATED_ANNOTATION =
      "@javax.annotation.processing.Generated(value = \"io.skis.processor.SkisEntityProcessor\", comments = \"ABI "
          + GENERATED_ABI
          + "\")\n";
  private static final char[] HEX_DIGITS = "0123456789abcdef".toCharArray();

  private SourceText() {}

  static String string(String value) {
    StringBuilder escaped = new StringBuilder(value.length() + 2);
    escaped.append('"');
    for (int index = 0; index < value.length(); index++) {
      char character = value.charAt(index);
      switch (character) {
        case '\\' -> escaped.append("\\\\");
        case '"' -> escaped.append("\\\"");
        case '\b' -> escaped.append("\\b");
        case '\n' -> escaped.append("\\n");
        case '\f' -> escaped.append("\\f");
        case '\r' -> escaped.append("\\r");
        case '\t' -> escaped.append("\\t");
        default -> {
          if (Character.isISOControl(character)) {
            appendOctalEscape(escaped, character);
          } else if (Character.isSurrogate(character)
              || character == '\u2028'
              || character == '\u2029') {
            appendUnicodeEscape(escaped, character);
          } else {
            escaped.append(character);
          }
        }
      }
    }
    return escaped.append('"').toString();
  }

  static String constantName(String value) {
    StringBuilder result = new StringBuilder(value.length() + 8);
    for (int index = 0; index < value.length(); index++) {
      char current = value.charAt(index);
      boolean uppercase = Character.isUpperCase(current);
      if (uppercase
          && index > 0
          && (Character.isLowerCase(value.charAt(index - 1))
              || Character.isDigit(value.charAt(index - 1))
              || (index + 1 < value.length() && Character.isLowerCase(value.charAt(index + 1))))) {
        result.append('_');
      }
      result.append(Character.toLowerCase(current));
    }
    return result.toString().toUpperCase(Locale.ROOT);
  }

  private static void appendOctalEscape(StringBuilder target, char character) {
    target.append('\\');
    target.append((char) ('0' + (character >>> 6 & 0x7)));
    target.append((char) ('0' + (character >>> 3 & 0x7)));
    target.append((char) ('0' + (character & 0x7)));
  }

  private static void appendUnicodeEscape(StringBuilder target, char character) {
    target.append("\\u");
    target.append(HEX_DIGITS[character >>> 12 & 0xF]);
    target.append(HEX_DIGITS[character >>> 8 & 0xF]);
    target.append(HEX_DIGITS[character >>> 4 & 0xF]);
    target.append(HEX_DIGITS[character & 0xF]);
  }
}
