<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.xhufang</groupId>
    <artifactId>skis-parent</artifactId>
    <version>0.0.8-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>skis-schema</artifactId>
  <name>skis-schema</name>
  <description>Schema reading, validation, diffing, and safe DDL export</description>
  <dependencies>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-metadata</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-dialect-api</artifactId>
    </dependency>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-jdbc</artifactId>
    </dependency>
  </dependencies>
</project>
