<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.xhufang</groupId>
    <artifactId>skis-parent</artifactId>
    <version>0.0.6-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>skis-cache-api</artifactId>
  <name>skis-cache-api</name>
  <description>Object, association, and computed-result cache SPIs</description>
  <dependencies>
    <dependency>
      <groupId>io.github.xhufang</groupId>
      <artifactId>skis-core</artifactId>
    </dependency>
  </dependencies>
</project>
