<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.xhufang</groupId>
    <artifactId>skis-benchmark</artifactId>
    <version>0.1.6-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>skis-benchmark-mybatisplus</artifactId>
  <name>skis-benchmark-mybatisplus</name>
  <description>MyBatis-Plus benchmark implementation</description>

  <dependencies>
    <dependency>
      <groupId>com.baomidou</groupId>
      <artifactId>mybatis-plus-core</artifactId>
    </dependency>
  </dependencies>
</project>
