<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.xhufang</groupId>
    <artifactId>skis-benchmark</artifactId>
    <version>0.2.2-SNAPSHOT</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>skis-benchmark-jooq</artifactId>
  <name>skis-benchmark-jooq</name>
  <description>jOOQ benchmark implementation</description>

  <dependencies>
    <dependency>
      <groupId>org.jooq</groupId>
      <artifactId>jooq</artifactId>
    </dependency>
  </dependencies>
</project>
